CREATE TABLE `ms_assets` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `tenant_id` bigint(20) DEFAULT NULL COMMENT '机构ID',
  `assets_id` bigint(20) DEFAULT NULL COMMENT '设备id',
  `img_url` varchar(300) DEFAULT NULL COMMENT '资产图片',
  `assets_name` varchar(50) DEFAULT NULL COMMENT '设备名称',
  `assets_dept_id` bigint(20) DEFAULT NULL COMMENT '设备所在科室id',
  `assets_dept_name` varchar(50) DEFAULT NULL COMMENT '设备所在科室名称',
  `assets_num` varchar(50) DEFAULT NULL COMMENT '设备编号',
  `assets_spec` varchar(50) DEFAULT NULL COMMENT '设备型号',
  `measure_num` varchar(50) DEFAULT NULL COMMENT '计量编号',
  `factory_id` int(11) DEFAULT NULL COMMENT '生产商ID',
  `factory_name` varchar(100) DEFAULT NULL COMMENT '生产商',
  `factory_num` varchar(50) DEFAULT NULL COMMENT '出厂编号',
  `serial_num` varchar(50) DEFAULT NULL COMMENT '院内编码',
  `spl_id` int(11) DEFAULT NULL COMMENT '供应商ID',
  `spl_name` varchar(200) DEFAULT NULL COMMENT '供货单位名称',
  `measure_type` int(1) DEFAULT NULL COMMENT '计量类别（1，A类 2，B类 3，C类）',
  `measure_category` int(1) DEFAULT NULL COMMENT '计量分类',
  `measure_cycle` int(2) DEFAULT NULL COMMENT '计量周期(单位月)',
  `next_check_time` datetime DEFAULT NULL COMMENT '下次检定日期',
  `check_mode` int(1) DEFAULT NULL COMMENT '检定方式（1，院内 2，外包）',
  `charge_user_id` bigint(20) DEFAULT NULL COMMENT '负责人ID',
  `charge_user_name` varchar(50) DEFAULT NULL COMMENT '负责人姓名',
  `remarks` varchar(300) DEFAULT NULL COMMENT '备注',
  `status` int(1) DEFAULT NULL COMMENT '状态（1，待完善 2，已完善）',
  `assets_status` int(1) DEFAULT NULL COMMENT '状态：1=在库、2=在用、3=预登、4=待报损、5=报损、6=退货''',
  `assets_type` int(1) DEFAULT NULL COMMENT '计量资产种类（1，固定 2，非固定）',
  `measure_manage_type` int(1) DEFAULT NULL COMMENT '管理类别（1，非强制性计量设备 2，强制性计量设备）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `del_flag` bit(1) DEFAULT b'0' COMMENT '作废标记，0：启用，1：删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='计量设备信息表';

CREATE TABLE `ms_check` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `measure_assets_id` bigint(20) DEFAULT NULL COMMENT '计量设备ID',
  `tenant_id` bigint(20) DEFAULT NULL COMMENT '机构ID',
  `assets_id` bigint(20) DEFAULT NULL COMMENT '设备id',
  `img_url` varchar(300) DEFAULT NULL COMMENT '资产图片',
  `assets_name` varchar(50) DEFAULT NULL COMMENT '设备名称',
  `assets_dept_id` bigint(20) DEFAULT NULL COMMENT '设备所在科室id',
  `assets_dept_name` varchar(50) DEFAULT NULL COMMENT '设备所在科室名称',
  `assets_num` varchar(50) DEFAULT NULL COMMENT '设备编号',
  `assets_spec` varchar(50) DEFAULT NULL COMMENT '设备型号',
  `measure_num` varchar(50) DEFAULT NULL COMMENT '计量编号',
  `factory_id` int(11) DEFAULT NULL COMMENT '生产商ID',
  `factory_name` varchar(100) DEFAULT NULL COMMENT '生产商',
  `factory_num` varchar(50) DEFAULT NULL COMMENT '出厂编号',
  `serial_num` varchar(50) DEFAULT NULL COMMENT '院内编码',
  `spl_id` int(11) DEFAULT NULL COMMENT '供应商ID',
  `spl_name` varchar(200) DEFAULT NULL COMMENT '供货单位名称',
  `measure_type` int(1) DEFAULT NULL COMMENT '计量类别（1，A类 2，B类 3，C类）',
  `measure_category` int(1) DEFAULT NULL COMMENT '计量分类',
  `measure_cycle` int(2) DEFAULT NULL COMMENT '计量周期(单位月)',
  `next_check_time` datetime DEFAULT NULL COMMENT '下次检定日期',
  `check_mode` int(1) DEFAULT NULL COMMENT '检定方式（1，院内 2，外包）',
  `charge_user_id` bigint(20) DEFAULT NULL COMMENT '负责人ID',
  `assets_status` int(1) DEFAULT NULL COMMENT '状态：1=在库、2=在用、3=预登、4=待报损、5=报损、6=退货''',
  `check_status` int(1) DEFAULT NULL COMMENT '检查状态（0=未检测，1=检测中）',
  `charge_user_name` varchar(50) DEFAULT NULL COMMENT '负责人姓名',
  `remarks` varchar(300) DEFAULT NULL COMMENT '备注',
  `assets_type` int(1) DEFAULT NULL COMMENT '计量资产种类（1，固定 2，非固定）',
  `measure_manage_type` int(1) DEFAULT NULL COMMENT '管理类别（1，非强制性计量设备 2，强制性计量设备）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='计量检测信息表(正在检测)';

CREATE TABLE `ms_check_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `measure_assets_id` bigint(20) DEFAULT NULL COMMENT '计量设备ID',
  `tenant_id` bigint(20) DEFAULT NULL COMMENT '机构ID',
  `assets_id` bigint(20) DEFAULT NULL COMMENT '设备id',
  `img_url` varchar(300) DEFAULT NULL COMMENT '资产图片',
  `assets_name` varchar(50) DEFAULT NULL COMMENT '设备名称',
  `assets_dept_id` bigint(20) DEFAULT NULL COMMENT '设备所在科室id',
  `assets_dept_name` varchar(50) DEFAULT NULL COMMENT '设备所在科室名称',
  `assets_num` varchar(50) DEFAULT NULL COMMENT '设备编号',
  `assets_spec` varchar(50) DEFAULT NULL COMMENT '设备型号',
  `measure_num` varchar(50) DEFAULT NULL COMMENT '计量编号',
  `factory_id` int(11) DEFAULT NULL COMMENT '生产商ID',
  `factory_name` varchar(100) DEFAULT NULL COMMENT '生产商',
  `factory_num` varchar(50) DEFAULT NULL COMMENT '出厂编号',
  `serial_num` varchar(50) DEFAULT NULL COMMENT '院内编码',
  `spl_id` int(11) DEFAULT NULL COMMENT '供应商ID',
  `spl_name` varchar(200) DEFAULT NULL COMMENT '供货单位名称',
  `measure_type` int(1) DEFAULT NULL COMMENT '计量类别（1，A类 2，B类 3，C类）',
  `measure_category` int(1) DEFAULT NULL COMMENT '计量分类',
  `measure_cycle` int(2) DEFAULT NULL COMMENT '计量周期(单位月)',
  `next_check_time` datetime DEFAULT NULL COMMENT '下次检定日期',
  `check_mode` int(1) DEFAULT NULL COMMENT '检定方式（1，院内 2，外包）',
  `charge_user_id` bigint(20) DEFAULT NULL COMMENT '负责人ID',
  `charge_user_name` varchar(50) DEFAULT NULL COMMENT '负责人姓名',
  `remarks` varchar(300) DEFAULT NULL COMMENT '备注',
  `assets_status` int(1) DEFAULT NULL COMMENT '状态：1=在库、2=在用、3=预登、4=待报损、5=报损、6=退货''',
  `assets_type` int(1) DEFAULT NULL COMMENT '计量资产种类（1，固定 2，非固定）',
  `measure_manage_type` int(1) DEFAULT NULL COMMENT '管理类别（1，非强制性计量设备 2，强制性计量设备）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='计量检测信息表(已检测)';

CREATE TABLE `ms_check_result_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `check_report_no` char(16) DEFAULT NULL COMMENT '报告编号',
  `check_history_id` bigint(20) DEFAULT NULL COMMENT '检测ID',
  `check_mode` int(1) DEFAULT NULL COMMENT '实际检定方式（1，院内 2，外包）',
  `certificate_num` varchar(40) DEFAULT NULL COMMENT '证书编号',
  `current_check_time` datetime DEFAULT NULL COMMENT '本次检测日期',
  `next_check_time` datetime DEFAULT NULL COMMENT '下次检测日期',
  `check_form` int(1) DEFAULT NULL COMMENT '检定形式（1，首次 2，随后 3，使用中检测 4，周期 5，仲裁）',
  `check_result_status` int(1) DEFAULT NULL COMMENT '检测结果（1，合格 2，准用 3，限用 4，禁用）',
  `check_organization` varchar(50) DEFAULT NULL COMMENT '检定机构',
  `check_fee` double(20,2) DEFAULT NULL COMMENT '检定费用',
  `check_user_name` varchar(50) DEFAULT NULL COMMENT '检定人',
  `auditor` varchar(50) DEFAULT NULL COMMENT '审核人',
  `remarks` varchar(300) DEFAULT NULL COMMENT '备注',
  `files` varchar(1000) DEFAULT NULL COMMENT '附件 以逗号分割',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='计量设备检测结果信息表(已检测)';

CREATE TABLE `ms_check_storage` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ms_check_id` bigint(20) DEFAULT NULL COMMENT '检测ID',
  `check_mode` int(1) DEFAULT NULL COMMENT '实际检定方式（1，院内 2，外包）',
  `certificate_num` varchar(20) DEFAULT NULL COMMENT '证书编号',
  `current_check_time` datetime DEFAULT NULL COMMENT '本次检测日期',
  `next_check_time` datetime DEFAULT NULL COMMENT '下次检测日期',
  `check_form` int(1) DEFAULT NULL COMMENT '检定形式（1，首次 2，随后 3，使用中检测 4，周期 5，仲裁）',
  `check_result_status` int(1) DEFAULT NULL COMMENT '检测结果（1，合格 2，准用 3，限用 4，禁用）',
  `check_organization` varchar(50) DEFAULT NULL COMMENT '检定机构',
  `check_fee` double(20,2) DEFAULT NULL COMMENT '检定费用',
  `check_user_name` varchar(50) DEFAULT NULL COMMENT '检定人',
  `auditor` varchar(50) DEFAULT NULL COMMENT '审核人',
  `remarks` varchar(300) DEFAULT NULL COMMENT '备注',
  `files` varchar(1000) DEFAULT NULL COMMENT '附件 以逗号分割',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='计量设备检测信息暂存表(正在检测)';





